#!/usr/bin/python3
def raise_exception():
    res = 10 / '2'
    return res
